# DO NOT CHANGE THE FIRST 2 SETTINGS
firstRun: true
firstRunDone: false
debugCommands: true
enable: true
enableLobbyProtection: false
ignoreWorlds:
  - world_the_end
  - world_nether
dedicatedSSB: false
jumpPower: 1
jumpInLobby: true
classesEnabled:
  - Creeper

